version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      all-dependencies:
        title: 'chore(deps): bump all dependencies'
        patterns:
          - '*'
    commit-message:
      prefix: 'chore(deps)'
